version: '3'

services:
  finalexam-mariadb:
    image: mariadb
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: exam
      MYSQL_USER: exam
      MYSQL_PASSWORD: exam
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  finalexam-app:
    image: finalexam
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - finalexam-mariadb
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mariadb://finalexam-mariadb/exam'
    entrypoint: ['./wait-for-it.sh', '-t', '120','finalexam-mariadb:3306','--','java','org.springframework.boot.loader.JarLauncher']